// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketSystem.DiscordBot.Databases.Tickets;

namespace TicketSystem.DiscordBot.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    partial class TicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("TicketSystem.DiscordBot.Databases.Tickets.Models.TicketCategory", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("CategoryId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("TicketCount")
                        .HasColumnType("int");

                    b.HasKey("GuildId");

                    b.ToTable("TicketCategories");
                });

            modelBuilder.Entity("TicketSystem.DiscordBot.Databases.Tickets.Models.TicketChannel", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("OpeningUserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("TicketChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
